# Generated by Django 4.1.7 on 2023-12-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TimeField(max_length=100)),
                ('publish', models.DateField()),
                ('cover', models.TextField(default='https://www.charitycomms.org.uk/wp-content/uploads/2019/02/placeholder-image-square.jpg')),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('album', models.TextField(max_length=100)),
                ('length', models.IntegerField()),
                ('rating', models.FloatField()),
                ('collab', models.TextField(choices=[('C', 'Collaboration'), ('S', 'Single')], default='S', max_length=1)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'ordering': ['-album'],
            },
        ),
    ]
