# Generated by Django 4.1.7 on 2023-12-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
