# Generated by Django 4.1.7 on 2023-12-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_albums_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='link',
            field=models.TextField(default='', max_length=500),
        ),
    ]
